name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-14"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmI5MjZjYWYtZTliMC00ODBhLTg0MmUtNzFjMGViYzAxNTlmIiwidGVuYW50X2lkIjoiNWYzNmM1M2ZhNjc0N2Y5ZTVkZGYxODk4N2Y4NjNlNDIxNmJlMTg1YWE0MDZhYmZkNmEyMmQyNDE4M2EwMjRmMCIsImludGVybmFsX3NlY3JldCI6Ijg3MjQxNGFmLWIyN2EtNGU3YS05ZDgyLTI0OWNjNTE5MjNmMiJ9._J7je4osuZo_EyLXVlAOlATvLvwh92sJ_r6vNoKwknk"
JWT_SECRET="ayushsecret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1